version: "3.9"
services:
  front:
    build: 
        context: ./frontend
        dockerfile: Dockerfile
    container_name: frontend
    ports:
        - "666:80"
  back:
    build: 
        context: ./backend
        dockerfile: Dockerfile
    tty: true
    container_name: backend
    ports:
        - "8000:8000"